### ISSUE TITLE
error when opening video

### ISSUE THREAD

**Issue by KalvinThien** [kuromifanboi/Tiktok-Video-Downloader#1]
The video can be downloaded, but when I open it, I get an error like this picture. do wrong to fix? thank you
![image](https://github.com/FurrieCoder/Tiktok-Video-Downloader/assets/120565705/0becb626-d076-4a6b-9675-0e13bcf88ea1)

**Comment by kuromifanboi** [comment]
Hi @KalvinThien I looked over my code and made some changes. I don't think that it's your video player causing issues, but how the video is grabbed using the plugin. I made some major code changes just now! Let me know if it helps

**Comment by kuromifanboi** [comment]
Hi @KalvinThien I created a V2 version of this plugin. I deleted V1 because it had issues with video handling and proper downloading. I revamped it to work on WordPress Version 6.5.3. You can download the V2 version here: https://github.com/kuromifanboi/Tiktok-Video-Downloader/releases/tag/Latest

I'm closing the issue, but if it still doesn't work let me know!
